[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload-url"
  status = 200
  force = true

[[redirects]]
  from = "/api/submit-swap"
  to = "/.netlify/functions/submit-swap"
  status = 200
  force = true

[[redirects]]
  from = "/api/submit-sell"
  to = "/.netlify/functions/submit-sell"
  status = 200
  force = true

[[redirects]]
  from = "/api/submit-repair"
  to = "/.netlify/functions/submit-repair"
  status = 200
  force = true

[[redirects]]
  from = "/api/submit-order"
  to = "/.netlify/functions/submit-order"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
