// generated by scripts/build-vercel-functions.mjs - do not edit
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// scripts/.entries/admin-ops.ts
var admin_ops_exports = {};
__export(admin_ops_exports, {
  default: () => admin_ops_default
});
module.exports = __toCommonJS(admin_ops_exports);

// netlify/functions/shared/cors.ts
function defaultOrigins() {
  const envOrigins = (process.env.ALLOWED_ORIGINS || "").split(",").map((o) => o.trim()).filter(Boolean);
  const siteUrl = process.env.URL;
  const vercelUrl = process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "";
  return [
    ...siteUrl ? [siteUrl] : [],
    ...vercelUrl ? [vercelUrl] : [],
    ...envOrigins,
    "http://localhost:3000",
    "http://localhost:5173"
  ];
}
function isSameOrigin(requestOrigin, event) {
  const host = event?.headers?.host || event?.headers?.["Host"];
  if (!host) return false;
  return requestOrigin === `https://${host}` || requestOrigin === `http://${host}`;
}
function isAllowedOrigin(requestOrigin, event) {
  if (!requestOrigin) return false;
  return defaultOrigins().includes(requestOrigin) || isSameOrigin(requestOrigin, event);
}
function corsHeaders(origin) {
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Vary": "Origin"
  };
}
function corsPreflight(origin) {
  return {
    statusCode: 204,
    headers: {
      ...corsHeaders(origin),
      "Access-Control-Max-Age": "86400"
    },
    body: ""
  };
}
function corsError(statusCode, message, origin) {
  return {
    statusCode,
    headers: corsHeaders(origin),
    body: JSON.stringify({ error: message })
  };
}
function getRequestOrigin(event) {
  return event.headers?.origin || event.headers?.["Origin"] || "unknown";
}

// netlify/functions/shared/rate-limit.ts
var rateBuckets = /* @__PURE__ */ new Map();
var RATE_LIMIT_MAX = 30;
var RATE_LIMIT_WINDOW_MS = 5 * 60 * 1e3;
function getClientIp(event) {
  return event.headers?.["x-nf-client-connection-ip"] || event.headers?.["x-forwarded-for"]?.split(",")[0] || "unknown";
}
function isRateLimited(ip) {
  const now = Date.now();
  const windowStart = now - RATE_LIMIT_WINDOW_MS;
  const hits = (rateBuckets.get(ip) || []).filter((t) => t > windowStart);
  if (hits.length >= RATE_LIMIT_MAX) {
    rateBuckets.set(ip, hits);
    return true;
  }
  hits.push(now);
  rateBuckets.set(ip, hits);
  return false;
}

// netlify/functions/shared/notify-admin.ts
function getSupabaseConfig() {
  const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;
  return { supabaseUrl, supabaseKey };
}

// netlify/functions/admin-ops.ts
var handler = async (event) => {
  const requestOrigin = getRequestOrigin(event);
  if (event.httpMethod === "OPTIONS") {
    if (!isAllowedOrigin(requestOrigin, event)) return { statusCode: 403, body: "Forbidden" };
    return corsPreflight(requestOrigin);
  }
  if (event.httpMethod !== "POST") {
    return corsError(405, "Method Not Allowed", requestOrigin);
  }
  if (!isAllowedOrigin(requestOrigin, event)) {
    return corsError(403, "Origin not allowed", requestOrigin);
  }
  const ip = getClientIp(event);
  if (isRateLimited(ip)) {
    return corsError(429, "Too many requests, please try again later", requestOrigin);
  }
  const { supabaseUrl, supabaseKey } = getSupabaseConfig();
  if (!supabaseUrl || !supabaseKey) {
    return corsError(500, "Server configuration error", requestOrigin);
  }
  const headers = {
    "Content-Type": "application/json",
    "apikey": supabaseKey,
    "Authorization": `Bearer ${supabaseKey}`
  };
  const post = (payload) => fetch(`${supabaseUrl}/rest/v1`, {
    method: "POST",
    headers: { ...headers, Prefer: "return=minimal" },
    body: JSON.stringify(payload)
  });
  const ok = (payload) => ({
    statusCode: 200,
    headers: corsHeaders(requestOrigin),
    body: JSON.stringify(payload)
  });
  const fail = (message) => corsError(500, message, requestOrigin);
  try {
    const body = JSON.parse(event.body || "{}");
    const { action } = body;
    switch (action) {
      // -------------------------------------------------------------
      case "fetchAll": {
        const [productsRes, ordersRes, profilesRes, subsRes, swapsRes, sellsRes, repairsRes] = await Promise.all([
          fetch(`${supabaseUrl}/rest/v1/products?order=created_at.desc&select=*`, { headers }),
          fetch(`${supabaseUrl}/rest/v1/orders?order=created_at.desc&select=*`, { headers }),
          fetch(`${supabaseUrl}/rest/v1/profiles?select=*`, { headers }),
          fetch(`${supabaseUrl}/rest/v1/newsletter_subscribers?order=created_at.desc&select=*`, { headers }),
          fetch(`${supabaseUrl}/rest/v1/swap_requests?order=created_at.desc&select=*`, { headers }),
          fetch(`${supabaseUrl}/rest/v1/sell_requests?order=created_at.desc&select=*`, { headers }),
          fetch(`${supabaseUrl}/rest/v1/repair_requests?order=created_at.desc&select=*`, { headers })
        ]);
        const json = async (r) => r.ok ? r.json() : [];
        const products = await json(productsRes);
        const orders = await json(ordersRes);
        const profiles = await json(profilesRes);
        const subscribers = await json(subsRes);
        const swaps = await json(swapsRes);
        const sells = await json(sellsRes);
        const repairs = await json(repairsRes);
        const customers = profiles.map((profile) => {
          const userOrders = orders.filter((o) => o.user_id === profile.id);
          const totalSpend = userOrders.filter((o) => o.status !== "cancelled").reduce((acc, o) => acc + o.total_price, 0);
          return {
            id: profile.id,
            email: profile.email,
            full_name: profile.full_name,
            total_spend: totalSpend,
            order_count: userOrders.length,
            last_order: userOrders[0]?.created_at || null
          };
        }).sort((a, b) => b.total_spend - a.total_spend);
        return ok({ products, orders, customers, subscribers, swaps, sells, repairs });
      }
      // -------------------------------------------------------------
      case "saveProduct": {
        const { product, isEditing } = body;
        if (!product?.name || product?.price == null) {
          return corsError(400, "Product name and price are required", requestOrigin);
        }
        const payload = {
          name: product.name,
          price: product.price,
          category: product.category,
          condition: product.condition || "New",
          description: product.description ?? null,
          image_url: product.image_url ?? null,
          image_url_2: product.image_url_2 ?? null,
          stock: product.stock || 0,
          swap_allowed: !!product.swap_allowed
        };
        if (isEditing && product.id) {
          const res = await fetch(`${supabaseUrl}/rest/v1/products?id=eq.${product.id}`, {
            method: "PATCH",
            headers,
            body: JSON.stringify(payload)
          });
          if (!res.ok) return fail("Failed to update product");
        } else {
          const res = await fetch(`${supabaseUrl}/rest/v1/products`, {
            method: "POST",
            headers: { ...headers, Prefer: "return=minimal" },
            body: JSON.stringify(payload)
          });
          if (!res.ok) return fail("Failed to add product");
        }
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "deleteProduct": {
        const { id } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/products?id=eq.${id}`, {
          method: "DELETE",
          headers
        });
        if (!res.ok) return fail("Failed to delete product");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "updateOrderStatus": {
        const { id, status } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/orders?id=eq.${id}`, {
          method: "PATCH",
          headers,
          body: JSON.stringify({ status })
        });
        if (!res.ok) return fail("Failed to update order status");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "acceptSwap": {
        const { id, tradeInValue, cashDifference, terms, notifiedAt } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/swap_requests?id=eq.${id}`, {
          method: "PATCH",
          headers,
          body: JSON.stringify({
            status: "accepted",
            trade_in_value: tradeInValue ?? null,
            cash_difference: cashDifference ?? null,
            terms: terms || null,
            notified_at: notifiedAt || (/* @__PURE__ */ new Date()).toISOString()
          })
        });
        if (!res.ok) return fail("Failed to accept swap");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "declineSwap": {
        const { id } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/swap_requests?id=eq.${id}`, {
          method: "PATCH",
          headers,
          body: JSON.stringify({ status: "declined" })
        });
        if (!res.ok) return fail("Failed to decline swap");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "deleteSwap": {
        const { id } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/swap_requests?id=eq.${id}`, {
          method: "DELETE",
          headers
        });
        if (!res.ok) return fail("Failed to delete swap");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "updateSellStatus": {
        const { id, status } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/sell_requests?id=eq.${id}`, {
          method: "PATCH",
          headers,
          body: JSON.stringify({ status })
        });
        if (!res.ok) return fail("Failed to update sell request");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "deleteSell": {
        const { id } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/sell_requests?id=eq.${id}`, {
          method: "DELETE",
          headers
        });
        if (!res.ok) return fail("Failed to delete sell request");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "saveDiagnosis": {
        const { id, diagnosis, cost, eta } = body;
        const payload = {
          status: "diagnosed",
          diagnosis: diagnosis?.trim() || null,
          repair_cost: cost ?? null,
          estimated_completion: eta ? new Date(eta).toISOString() : null
        };
        const res = await fetch(`${supabaseUrl}/rest/v1/repair_requests?id=eq.${id}`, {
          method: "PATCH",
          headers,
          body: JSON.stringify(payload)
        });
        if (!res.ok) return fail("Failed to save diagnosis");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "updateRepairStatus": {
        const { id, status } = body;
        const payload = { status };
        if (status === "picked_up") payload.completed_at = (/* @__PURE__ */ new Date()).toISOString();
        const res = await fetch(`${supabaseUrl}/rest/v1/repair_requests?id=eq.${id}`, {
          method: "PATCH",
          headers,
          body: JSON.stringify(payload)
        });
        if (!res.ok) return fail("Failed to update repair status");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "declineRepair": {
        const { id, reason } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/repair_requests?id=eq.${id}`, {
          method: "PATCH",
          headers,
          body: JSON.stringify({ status: "declined", decline_reason: reason?.trim() || null })
        });
        if (!res.ok) return fail("Failed to decline repair");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "deleteRepair": {
        const { id } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/repair_requests?id=eq.${id}`, {
          method: "DELETE",
          headers
        });
        if (!res.ok) return fail("Failed to delete repair request");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "createNotification": {
        const { notification } = body;
        if (!notification?.userId) return corsError(400, "userId required", requestOrigin);
        const res = await fetch(`${supabaseUrl}/rest/v1/notifications`, {
          method: "POST",
          headers: { ...headers, Prefer: "return=minimal" },
          body: JSON.stringify({
            user_id: notification.userId,
            type: notification.type || "general",
            title: notification.title || "Notification",
            message: notification.message || "",
            read: false
          })
        });
        if (!res.ok) return fail("Failed to create notification");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "deleteSubscriber": {
        const { id } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/newsletter_subscribers?id=eq.${id}`, {
          method: "DELETE",
          headers
        });
        if (!res.ok) return fail("Failed to remove subscriber");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      default:
        return corsError(400, `Unknown action: ${action}`, requestOrigin);
    }
  } catch (error) {
    console.error("Admin ops error:", error);
    return corsError(500, "Internal Server Error", requestOrigin);
  }
};

// api/_lib/adapter.ts
async function runHandler(handler2, req, res) {
  const rawReq = req;
  const hasWebBodyReader = typeof rawReq?.text === "function";
  const method = hasWebBodyReader ? rawReq.method : rawReq?.method || "POST";
  let body = "";
  const headers = {};
  try {
    if (hasWebBodyReader) {
      body = await rawReq.text();
      if (rawReq.headers && typeof rawReq.headers.forEach === "function") {
        rawReq.headers.forEach((value, key) => {
          headers[key] = value;
        });
      }
    } else {
      const rawBody = rawReq?.body;
      if (typeof rawBody === "string") body = rawBody;
      else if (rawBody && typeof rawBody === "object") body = JSON.stringify(rawBody);
      const httpHeaders = rawReq?.headers || {};
      for (const key of Object.keys(httpHeaders)) {
        const value = httpHeaders[key];
        headers[key] = Array.isArray(value) ? value.join(", ") : String(value ?? "");
      }
    }
  } catch (error) {
    console.error("[api] Failed to read request:", error);
    return respondWith({ statusCode: 400, headers: {}, body: JSON.stringify({ error: `Invalid request: ${error?.message || error}` }) }, res);
  }
  const event = {
    httpMethod: String(method || "POST").toUpperCase(),
    headers,
    body,
    queryStringParameters: rawReq?.query || {}
  };
  let result;
  try {
    result = await handler2(event, {});
  } catch (error) {
    console.error("[api] Handler threw:", error);
    return respondWith(
      {
        statusCode: 500,
        headers: {},
        body: JSON.stringify({ error: `Handler error: ${error?.message || error}` })
      },
      res
    );
  }
  const statusCode = result?.statusCode || 200;
  const responseBody = result?.body || "";
  const applyHeaders = (target) => {
    const resultHeaders = { ...result?.headers || {} };
    if (!("Content-Type" in resultHeaders) && responseBody) {
      resultHeaders["Content-Type"] = "application/json";
    }
    for (const [key, value] of Object.entries(resultHeaders)) {
      target[key] = value;
    }
  };
  if (res && typeof res.end === "function") {
    const nodeRes = res;
    if (typeof nodeRes.status === "function") nodeRes.status(statusCode);
    else nodeRes.statusCode = statusCode;
    applyHeaders(nodeRes);
    nodeRes.end(responseBody);
    return;
  }
  const responseHeaders = new Headers();
  applyHeaders(responseHeaders);
  return new Response(responseBody, { status: statusCode, headers: responseHeaders });
}
function respondWith(result, res) {
  const statusCode = result.statusCode || 500;
  const responseBody = result.body || "";
  const applyHeaders = (target) => {
    const resultHeaders = { ...result.headers || {} };
    if (!("Content-Type" in resultHeaders) && responseBody) {
      resultHeaders["Content-Type"] = "application/json";
    }
    for (const [key, value] of Object.entries(resultHeaders)) {
      target[key] = value;
    }
  };
  if (res && typeof res.end === "function") {
    if (typeof res.status === "function") res.status(statusCode);
    else res.statusCode = statusCode;
    applyHeaders(res);
    res.end(responseBody);
    return;
  }
  const responseHeaders = new Headers();
  applyHeaders(responseHeaders);
  return new Response(responseBody, { status: statusCode, headers: responseHeaders });
}

// scripts/.entries/admin-ops.ts
async function admin_ops_default(req, res) {
  return runHandler(handler, req, res);
}
module.exports = module.exports ? module.exports.default : module.exports;
