// generated by scripts/build-vercel-functions.mjs - do not edit

// netlify/functions/submit-sell.ts
var ALLOWED_ORIGINS = [
  "https://john20deals.netlify.app",
  "https://john20-deals.netlify.app",
  "http://localhost:3000",
  "http://localhost:5173"
];
var supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
var supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;
function getOrigin(requestOrigin) {
  return requestOrigin || "unknown";
}
function isAllowedOrigin(origin) {
  return ALLOWED_ORIGINS.includes(origin);
}
function errorResponse(statusCode, message, origin) {
  return {
    statusCode,
    headers: {
      "Access-Control-Allow-Origin": origin,
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
      "Vary": "Origin"
    },
    body: JSON.stringify({ error: message })
  };
}
var handler = async (event) => {
  const requestOrigin = getOrigin(event.headers?.origin || event.headers?.["Origin"]);
  if (event.httpMethod === "OPTIONS") {
    if (!isAllowedOrigin(requestOrigin)) return { statusCode: 403, body: "Forbidden" };
    return {
      statusCode: 204,
      headers: {
        "Access-Control-Allow-Origin": requestOrigin,
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type",
        "Access-Control-Max-Age": "86400",
        "Vary": "Origin"
      },
      body: ""
    };
  }
  if (event.httpMethod !== "POST") {
    return errorResponse(405, "Method Not Allowed", requestOrigin);
  }
  if (!isAllowedOrigin(requestOrigin)) {
    return errorResponse(403, "Origin not allowed", requestOrigin);
  }
  try {
    const body = JSON.parse(event.body || "{}");
    const {
      userId,
      userName,
      userPhone,
      deviceType,
      brand,
      model,
      condition,
      description,
      imageUrls
    } = body;
    if (!userId || !userName || !userPhone) {
      return errorResponse(400, "userId, userName and userPhone are required", requestOrigin);
    }
    if (!Array.isArray(imageUrls) || imageUrls.length > 3) {
      return errorResponse(400, "At most 3 images are allowed", requestOrigin);
    }
    if (userPhone && !/^\+?\d{8,15}$/.test(String(userPhone))) {
      return errorResponse(400, "Invalid phone number", requestOrigin);
    }
    if (!supabaseUrl || !supabaseKey) {
      return errorResponse(500, "Server configuration error", requestOrigin);
    }
    const response = await fetch(`${supabaseUrl}/rest/v1/sell_requests`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "apikey": supabaseKey,
        "Authorization": `Bearer ${supabaseKey}`,
        "Prefer": "return=representation"
      },
      body: JSON.stringify({
        user_id: userId,
        user_name: userName,
        user_phone: userPhone,
        device_type: deviceType || null,
        brand: brand || null,
        model: model || null,
        condition: condition || null,
        description: description || null,
        image_url_1: imageUrls?.[0] || null,
        image_url_2: imageUrls?.[1] || null,
        image_url_3: imageUrls?.[2] || null
      })
    });
    if (!response.ok) {
      const errorText = await response.text();
      console.error("Supabase insert error (sell_requests):", errorText.slice(0, 500));
      return errorResponse(500, "Failed to save sell request", requestOrigin);
    }
    const data = await response.json();
    return {
      statusCode: 200,
      headers: {
        "Access-Control-Allow-Origin": requestOrigin,
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type",
        "Vary": "Origin"
      },
      body: JSON.stringify({ success: true, sellRequestId: data[0]?.id })
    };
  } catch (error) {
    console.error("Sell request submission error:", error);
    return errorResponse(500, "Internal Server Error", requestOrigin);
  }
};

// api/_lib/adapter.ts
async function runHandler(handler2, req, res) {
  const rawReq = req;
  const hasWebBodyReader = typeof rawReq?.text === "function";
  const method = hasWebBodyReader ? rawReq.method : rawReq?.method || "POST";
  let body = "";
  const headers = {};
  try {
    if (hasWebBodyReader) {
      body = await rawReq.text();
      if (rawReq.headers && typeof rawReq.headers.forEach === "function") {
        rawReq.headers.forEach((value, key) => {
          headers[key] = value;
        });
      }
    } else {
      if (typeof rawReq?.body === "string") body = rawReq.body;
      else if (rawReq?.body && typeof rawReq.body === "object") {
        body = JSON.stringify(rawReq.body);
      } else {
        body = await readStream(rawReq);
      }
      const httpHeaders = rawReq?.headers || {};
      for (const key of Object.keys(httpHeaders)) {
        const value = httpHeaders[key];
        headers[key] = Array.isArray(value) ? value.join(", ") : String(value ?? "");
      }
    }
  } catch (error) {
    console.error("[api] Failed to read request:", error);
    return respondWith({ statusCode: 400, headers: {}, body: JSON.stringify({ error: `Invalid request: ${error?.message || error}` }) }, res);
  }
  const event = {
    httpMethod: String(method || "POST").toUpperCase(),
    headers,
    body,
    queryStringParameters: rawReq?.query || {}
  };
  let result;
  try {
    result = await handler2(event, {}) || {
      statusCode: 500,
      headers: {},
      body: JSON.stringify({ error: "Handler returned no response" })
    };
  } catch (error) {
    console.error("[api] Handler threw:", error);
    return respondWith(
      {
        statusCode: 500,
        headers: {},
        body: JSON.stringify({ error: `Handler error: ${error?.message || error}` })
      },
      res
    );
  }
  const statusCode = result?.statusCode || 200;
  const responseBody = result?.body || "";
  const applyHeaders = (target) => {
    const resultHeaders = { ...result?.headers || {} };
    if (!("Content-Type" in resultHeaders) && responseBody) {
      resultHeaders["Content-Type"] = "application/json";
    }
    for (const [key, value] of Object.entries(resultHeaders)) {
      target[key] = value;
    }
  };
  if (res && typeof res.end === "function") {
    const nodeRes = res;
    if (typeof nodeRes.statusCode === "number") nodeRes.statusCode = statusCode;
    if (typeof nodeRes.status === "function") nodeRes.status(statusCode);
    applyHeaders(nodeRes);
    nodeRes.end(responseBody);
    return;
  }
  const responseHeaders = new Headers();
  applyHeaders(responseHeaders);
  return new Response(responseBody, { status: statusCode, headers: responseHeaders });
}
function readStream(req) {
  return new Promise((resolve) => {
    if (!req || typeof req.on !== "function") return resolve("");
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", () => resolve(""));
  });
}
function respondWith(result, res) {
  const statusCode = result.statusCode || 500;
  const responseBody = result.body || "";
  const applyHeaders = (target) => {
    const resultHeaders = { ...result.headers || {} };
    if (!("Content-Type" in resultHeaders) && responseBody) {
      resultHeaders["Content-Type"] = "application/json";
    }
    for (const [key, value] of Object.entries(resultHeaders)) {
      target[key] = value;
    }
  };
  if (res && typeof res.end === "function") {
    if (typeof res.statusCode === "number") res.statusCode = statusCode;
    if (typeof res.status === "function") res.status(statusCode);
    applyHeaders(res);
    res.end(responseBody);
    return;
  }
  const responseHeaders = new Headers();
  applyHeaders(responseHeaders);
  return new Response(responseBody, { status: statusCode, headers: responseHeaders });
}

// scripts/.entries/submit-sell.ts
async function submit_sell_default(req, res) {
  return runHandler(handler, req, res);
}
export {
  submit_sell_default as default
};
