// generated by scripts/build-vercel-functions.mjs - do not edit
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// scripts/.entries/submit-swap.ts
var submit_swap_exports = {};
__export(submit_swap_exports, {
  default: () => submit_swap_default
});
module.exports = __toCommonJS(submit_swap_exports);

// netlify/functions/shared/cors.ts
function defaultOrigins() {
  const envOrigins = (process.env.ALLOWED_ORIGINS || "").split(",").map((o) => o.trim()).filter(Boolean);
  const siteUrl = process.env.URL;
  const vercelUrl = process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "";
  return [
    ...siteUrl ? [siteUrl] : [],
    ...vercelUrl ? [vercelUrl] : [],
    ...envOrigins,
    "http://localhost:3000",
    "http://localhost:5173"
  ];
}
function isSameOrigin(requestOrigin, event) {
  const host = event?.headers?.host || event?.headers?.["Host"];
  if (!host) return false;
  return requestOrigin === `https://${host}` || requestOrigin === `http://${host}`;
}
function isAllowedOrigin(requestOrigin, event) {
  if (!requestOrigin) return false;
  return defaultOrigins().includes(requestOrigin) || isSameOrigin(requestOrigin, event);
}
function corsHeaders(origin) {
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Vary": "Origin"
  };
}
function corsPreflight(origin) {
  return {
    statusCode: 204,
    headers: {
      ...corsHeaders(origin),
      "Access-Control-Max-Age": "86400"
    },
    body: ""
  };
}
function corsError(statusCode, message, origin) {
  return {
    statusCode,
    headers: corsHeaders(origin),
    body: JSON.stringify({ error: message })
  };
}
function getRequestOrigin(event) {
  return event.headers?.origin || event.headers?.["Origin"] || "unknown";
}

// netlify/functions/shared/rate-limit.ts
var rateBuckets = /* @__PURE__ */ new Map();
var RATE_LIMIT_MAX = 30;
var RATE_LIMIT_WINDOW_MS = 5 * 60 * 1e3;
function getClientIp(event) {
  return event.headers?.["x-nf-client-connection-ip"] || event.headers?.["x-forwarded-for"]?.split(",")[0] || "unknown";
}
function isRateLimited(ip) {
  const now = Date.now();
  const windowStart = now - RATE_LIMIT_WINDOW_MS;
  const hits = (rateBuckets.get(ip) || []).filter((t) => t > windowStart);
  if (hits.length >= RATE_LIMIT_MAX) {
    rateBuckets.set(ip, hits);
    return true;
  }
  hits.push(now);
  rateBuckets.set(ip, hits);
  return false;
}

// netlify/functions/shared/notify-admin.ts
function getSupabaseConfig() {
  const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;
  return { supabaseUrl, supabaseKey };
}
var LEGACY_ADMIN_EMAILS = ["rockwellsan7@gmail.com", "johndarkwah20@gmail.com"];
async function fetchAdminTargets() {
  const { supabaseUrl, supabaseKey } = getSupabaseConfig();
  if (!supabaseUrl || !supabaseKey) return [];
  try {
    const url = `${supabaseUrl}/rest/v1/profiles?role=eq.admin&select=id,email`;
    const response = await fetch(url, {
      headers: {
        apikey: supabaseKey,
        Authorization: `Bearer ${supabaseKey}`
      }
    });
    if (!response.ok) return [];
    const data = await response.json();
    const byRole = Array.isArray(data) ? data : [];
    const emails = new Set(byRole.map((p) => (p.email || "").toLowerCase()));
    for (const email of LEGACY_ADMIN_EMAILS) {
      if (!emails.has(email.toLowerCase())) byRole.push({ id: null, email });
    }
    return byRole.filter((p) => p.id || p.email);
  } catch (error) {
    console.error("Failed to fetch admin targets:", error);
    return [];
  }
}
async function notifyAdmins(input) {
  const { supabaseUrl, supabaseKey } = getSupabaseConfig();
  if (!supabaseUrl || !supabaseKey) return;
  const targets = await fetchAdminTargets();
  if (targets.length === 0) return;
  const payload = targets.map((t) => ({
    user_id: t.userId,
    type: input.type,
    title: input.title,
    message: input.message || null,
    read: false
  }));
  try {
    await fetch(`${supabaseUrl}/rest/v1/notifications`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: supabaseKey,
        Authorization: `Bearer ${supabaseKey}`,
        Prefer: "return=minimal"
      },
      body: JSON.stringify(payload)
    });
  } catch (error) {
    console.error("Failed to notify admins:", error);
  }
}

// netlify/functions/submit-swap.ts
var handler = async (event) => {
  const requestOrigin = getRequestOrigin(event);
  if (event.httpMethod === "OPTIONS") {
    if (!isAllowedOrigin(requestOrigin, event)) return { statusCode: 403, body: "Forbidden" };
    return corsPreflight(requestOrigin);
  }
  if (event.httpMethod !== "POST") {
    return corsError(405, "Method Not Allowed", requestOrigin);
  }
  if (!isAllowedOrigin(requestOrigin, event)) {
    return corsError(403, "Origin not allowed", requestOrigin);
  }
  const ip = getClientIp(event);
  if (isRateLimited(ip)) {
    return corsError(429, "Too many requests, please try again later", requestOrigin);
  }
  try {
    const body = JSON.parse(event.body || "{}");
    const {
      productId,
      productName,
      userId,
      userName,
      userPhone,
      description,
      imageUrls
    } = body;
    if (!productId || !userId) {
      return corsError(400, "productId and userId are required", requestOrigin);
    }
    if (!Array.isArray(imageUrls) || imageUrls.length > 3) {
      return corsError(400, "At most 3 images are allowed", requestOrigin);
    }
    if (userName && String(userName).length > 100) {
      return corsError(400, "Name is too long", requestOrigin);
    }
    if (userPhone && !/^\+?\d{8,15}$/.test(String(userPhone))) {
      return corsError(400, "Invalid phone number", requestOrigin);
    }
    if (description && String(description).length > 2e3) {
      return corsError(400, "Description is too long (max 2000 chars)", requestOrigin);
    }
    const { supabaseUrl, supabaseKey } = getSupabaseConfig();
    if (!supabaseUrl || !supabaseKey) {
      return corsError(500, "Server configuration error", requestOrigin);
    }
    const response = await fetch(`${supabaseUrl}/rest/v1/swap_requests`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "apikey": supabaseKey,
        "Authorization": `Bearer ${supabaseKey}`,
        "Prefer": "return=representation"
      },
      body: JSON.stringify({
        user_id: userId,
        user_name: userName || null,
        user_phone: userPhone || null,
        product_id: productId,
        product_name: productName || null,
        offer_description: description || null,
        image_url_1: imageUrls?.[0] || null,
        image_url_2: imageUrls?.[1] || null,
        image_url_3: imageUrls?.[2] || null
      })
    });
    if (!response.ok) {
      const errorText = await response.text();
      console.error("Supabase insert error (swap_requests):", errorText.slice(0, 500));
      return corsError(500, "Failed to save swap request", requestOrigin);
    }
    const data = await response.json();
    await notifyAdmins({
      type: "swap",
      title: "New swap proposal",
      message: `${userName || "A customer"} proposed a swap for ${productName || "a product"}.`
    });
    return {
      statusCode: 200,
      headers: corsHeaders(requestOrigin),
      body: JSON.stringify({ success: true, swapRequestId: data[0]?.id })
    };
  } catch (error) {
    console.error("Swap request submission error:", error);
    return corsError(500, "Internal Server Error", requestOrigin);
  }
};

// api/_lib/adapter.ts
async function runHandler(handler2, req, res) {
  const rawReq = req;
  const hasWebBodyReader = typeof rawReq?.text === "function";
  const method = hasWebBodyReader ? rawReq.method : rawReq?.method || "POST";
  let body = "";
  const headers = {};
  try {
    if (hasWebBodyReader) {
      body = await rawReq.text();
      if (rawReq.headers && typeof rawReq.headers.forEach === "function") {
        rawReq.headers.forEach((value, key) => {
          headers[key] = value;
        });
      }
    } else {
      const rawBody = rawReq?.body;
      if (typeof rawBody === "string") body = rawBody;
      else if (rawBody && typeof rawBody === "object") body = JSON.stringify(rawBody);
      const httpHeaders = rawReq?.headers || {};
      for (const key of Object.keys(httpHeaders)) {
        const value = httpHeaders[key];
        headers[key] = Array.isArray(value) ? value.join(", ") : String(value ?? "");
      }
    }
  } catch (error) {
    console.error("[api] Failed to read request:", error);
    return respondWith({ statusCode: 400, headers: {}, body: JSON.stringify({ error: `Invalid request: ${error?.message || error}` }) }, res);
  }
  const event = {
    httpMethod: String(method || "POST").toUpperCase(),
    headers,
    body,
    queryStringParameters: rawReq?.query || {}
  };
  let result;
  try {
    result = await handler2(event, {});
  } catch (error) {
    console.error("[api] Handler threw:", error);
    return respondWith(
      {
        statusCode: 500,
        headers: {},
        body: JSON.stringify({ error: `Handler error: ${error?.message || error}` })
      },
      res
    );
  }
  const statusCode = result?.statusCode || 200;
  const responseBody = result?.body || "";
  const applyHeaders = (target) => {
    const resultHeaders = { ...result?.headers || {} };
    if (!("Content-Type" in resultHeaders) && responseBody) {
      resultHeaders["Content-Type"] = "application/json";
    }
    for (const [key, value] of Object.entries(resultHeaders)) {
      target[key] = value;
    }
  };
  if (res && typeof res.end === "function") {
    const nodeRes = res;
    if (typeof nodeRes.status === "function") nodeRes.status(statusCode);
    else nodeRes.statusCode = statusCode;
    applyHeaders(nodeRes);
    nodeRes.end(responseBody);
    return;
  }
  const responseHeaders = new Headers();
  applyHeaders(responseHeaders);
  return new Response(responseBody, { status: statusCode, headers: responseHeaders });
}
function respondWith(result, res) {
  const statusCode = result.statusCode || 500;
  const responseBody = result.body || "";
  const applyHeaders = (target) => {
    const resultHeaders = { ...result.headers || {} };
    if (!("Content-Type" in resultHeaders) && responseBody) {
      resultHeaders["Content-Type"] = "application/json";
    }
    for (const [key, value] of Object.entries(resultHeaders)) {
      target[key] = value;
    }
  };
  if (res && typeof res.end === "function") {
    if (typeof res.status === "function") res.status(statusCode);
    else res.statusCode = statusCode;
    applyHeaders(res);
    res.end(responseBody);
    return;
  }
  const responseHeaders = new Headers();
  applyHeaders(responseHeaders);
  return new Response(responseBody, { status: statusCode, headers: responseHeaders });
}

// scripts/.entries/submit-swap.ts
async function submit_swap_default(req, res) {
  return runHandler(handler, req, res);
}
module.exports = module.exports ? module.exports.default : module.exports;
