// generated by scripts/build-vercel-functions.mjs - do not edit

// netlify/functions/shared/cors.ts
function defaultOrigins() {
  const envOrigins = (process.env.ALLOWED_ORIGINS || "").split(",").map((o) => o.trim()).filter(Boolean);
  const siteUrl = process.env.URL;
  const vercelUrl = process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "";
  return [
    ...siteUrl ? [siteUrl] : [],
    ...vercelUrl ? [vercelUrl] : [],
    ...envOrigins,
    "http://localhost:3000",
    "http://localhost:5173"
  ];
}
function isSameOrigin(requestOrigin, event) {
  const host = event?.headers?.host || event?.headers?.["Host"];
  if (!host) return false;
  return requestOrigin === `https://${host}` || requestOrigin === `http://${host}`;
}
function isAllowedOrigin(requestOrigin, event) {
  if (!requestOrigin) return false;
  return defaultOrigins().includes(requestOrigin) || isSameOrigin(requestOrigin, event);
}
function corsHeaders(origin) {
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Vary": "Origin"
  };
}
function corsPreflight(origin) {
  return {
    statusCode: 204,
    headers: {
      ...corsHeaders(origin),
      "Access-Control-Max-Age": "86400"
    },
    body: ""
  };
}
function corsError(statusCode, message, origin) {
  return {
    statusCode,
    headers: corsHeaders(origin),
    body: JSON.stringify({ error: message })
  };
}
function getRequestOrigin(event) {
  return event.headers?.origin || event.headers?.["Origin"] || "unknown";
}

// netlify/functions/shared/rate-limit.ts
var rateBuckets = /* @__PURE__ */ new Map();
var RATE_LIMIT_MAX = 30;
var RATE_LIMIT_WINDOW_MS = 5 * 60 * 1e3;
function getClientIp(event) {
  return event.headers?.["x-nf-client-connection-ip"] || event.headers?.["x-forwarded-for"]?.split(",")[0] || "unknown";
}
function isRateLimited(ip) {
  const now = Date.now();
  const windowStart = now - RATE_LIMIT_WINDOW_MS;
  const hits = (rateBuckets.get(ip) || []).filter((t) => t > windowStart);
  if (hits.length >= RATE_LIMIT_MAX) {
    rateBuckets.set(ip, hits);
    return true;
  }
  hits.push(now);
  rateBuckets.set(ip, hits);
  return false;
}

// netlify/functions/shared/notify-admin.ts
function getSupabaseConfig() {
  const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;
  return { supabaseUrl, supabaseKey };
}

// netlify/functions/user-ops.ts
var handler = async (event) => {
  const requestOrigin = getRequestOrigin(event);
  if (event.httpMethod === "OPTIONS") {
    if (!isAllowedOrigin(requestOrigin, event)) return { statusCode: 403, body: "Forbidden" };
    return corsPreflight(requestOrigin);
  }
  if (event.httpMethod !== "POST") {
    return corsError(405, "Method Not Allowed", requestOrigin);
  }
  if (!isAllowedOrigin(requestOrigin, event)) {
    return corsError(403, "Origin not allowed", requestOrigin);
  }
  const ip = getClientIp(event);
  if (isRateLimited(ip)) {
    return corsError(429, "Too many requests, please try again later", requestOrigin);
  }
  const { supabaseUrl, supabaseKey } = getSupabaseConfig();
  if (!supabaseUrl || !supabaseKey) {
    return corsError(500, "Server configuration error", requestOrigin);
  }
  const headers = {
    "Content-Type": "application/json",
    "apikey": supabaseKey,
    "Authorization": `Bearer ${supabaseKey}`
  };
  const ok = (payload) => ({
    statusCode: 200,
    headers: corsHeaders(requestOrigin),
    body: JSON.stringify(payload)
  });
  const fail = (message) => corsError(500, message, requestOrigin);
  try {
    const body = JSON.parse(event.body || "{}");
    const { action } = body;
    switch (action) {
      // -------------------------------------------------------------
      case "fetchUserData": {
        const { userId } = body;
        if (!userId) return corsError(400, "userId is required", requestOrigin);
        const filter = `user_id=eq.${encodeURIComponent(userId)}`;
        const [ordersRes, sellRes, repairRes, swapRes] = await Promise.all([
          fetch(`${supabaseUrl}/rest/v1/orders?${filter}&order=created_at.desc&select=*`, { headers }),
          fetch(`${supabaseUrl}/rest/v1/sell_requests?${filter}&order=created_at.desc&select=*`, { headers }),
          fetch(`${supabaseUrl}/rest/v1/repair_requests?${filter}&order=created_at.desc&select=*`, { headers }),
          fetch(`${supabaseUrl}/rest/v1/swap_requests?${filter}&order=created_at.desc&select=*`, { headers })
        ]);
        const json = async (r) => r.ok ? r.json() : [];
        return ok({
          orders: await json(ordersRes),
          sell: await json(sellRes),
          repair: await json(repairRes),
          swaps: await json(swapRes)
        });
      }
      // -------------------------------------------------------------
      case "fetchNotifications": {
        const { userId } = body;
        if (!userId) return corsError(400, "userId is required", requestOrigin);
        const filter = `user_id=eq.${encodeURIComponent(userId)}`;
        const [notifRes, profileRes] = await Promise.all([
          fetch(`${supabaseUrl}/rest/v1/notifications?${filter}&order=created_at.desc&select=*`, { headers }),
          fetch(`${supabaseUrl}/rest/v1/profiles?${filter}&select=*`, { headers })
        ]);
        const json = async (r) => r.ok ? r.json() : [];
        const notifications = await json(notifRes);
        const profiles = await json(profileRes);
        return ok({ notifications, unread: notifications.filter((n) => !n.read).length, profiles });
      }
      // -------------------------------------------------------------
      case "markNotificationsRead": {
        const { ids } = body;
        if (!Array.isArray(ids) || ids.length === 0) {
          return corsError(400, "ids required", requestOrigin);
        }
        const inFilter = ids.map((id) => `"${id}"`).join(",");
        const res = await fetch(`${supabaseUrl}/rest/v1/notifications?id=in.(${inFilter})`, {
          method: "PATCH",
          headers,
          body: JSON.stringify({ read: true })
        });
        if (!res.ok) return fail("Failed to update notifications");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "cancelRepair": {
        const { id } = body;
        const res = await fetch(`${supabaseUrl}/rest/v1/repair_requests?id=eq.${id}`, {
          method: "PATCH",
          headers,
          body: JSON.stringify({ status: "cancelled" })
        });
        if (!res.ok) return fail("Failed to cancel repair");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "syncProfile": {
        const { profile } = body;
        if (!profile?.id) return corsError(400, "Profile id required", requestOrigin);
        const payload = {
          id: profile.id,
          email: profile.email ?? null,
          full_name: profile.full_name ?? null,
          phone: profile.phone ?? null,
          location: profile.location ?? null,
          created_at: profile.created_at ?? (/* @__PURE__ */ new Date()).toISOString()
        };
        const res = await fetch(`${supabaseUrl}/rest/v1/profiles`, {
          method: "POST",
          headers: {
            ...headers,
            Prefer: "resolution=merge-duplicates,return=minimal"
          },
          body: JSON.stringify(payload)
        });
        if (!res.ok) return fail("Failed to sync profile");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "addReview": {
        const { review } = body;
        if (!review?.product_id) return corsError(400, "product_id required", requestOrigin);
        const res = await fetch(`${supabaseUrl}/rest/v1/reviews`, {
          method: "POST",
          headers: { ...headers, Prefer: "return=minimal" },
          body: JSON.stringify({
            product_id: review.product_id,
            user_id: review.user_id ?? null,
            author_name: review.author_name ?? null,
            rating: Math.min(5, Math.max(1, Number(review.rating) || 5)),
            comment: review.comment ?? null
          })
        });
        if (!res.ok) return fail("Failed to submit review");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      case "fetchReviews": {
        const { productId } = body;
        if (!productId) return corsError(400, "productId required", requestOrigin);
        const res = await fetch(
          `${supabaseUrl}/rest/v1/reviews?product_id=eq.${encodeURIComponent(productId)}&order=created_at.desc&select=*`,
          { headers }
        );
        const reviews = res.ok ? await res.json() : [];
        const userIds = reviews.map((r) => r.user_id).filter(Boolean);
        let profiles = [];
        if (userIds.length > 0) {
          const inFilter = userIds.map((id) => `"${id}"`).join(",");
          const profilesRes = await fetch(
            `${supabaseUrl}/rest/v1/profiles?id=in.(${inFilter})&select=*`,
            { headers }
          );
          if (profilesRes.ok) profiles = await profilesRes.json();
        }
        const profileMap = new Map(profiles.map((p) => [p.id, p]));
        const result = reviews.map((review) => {
          const profile = profileMap.get(review.user_id);
          return {
            ...review,
            profiles: {
              full_name: review.author_name || profile?.full_name || null,
              avatar_url: profile?.avatar_url || null
            }
          };
        });
        return ok({ reviews: result });
      }
      // -------------------------------------------------------------
      case "subscribeNewsletter": {
        const { email } = body;
        if (!email || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) {
          return corsError(400, "Valid email required", requestOrigin);
        }
        const res = await fetch(`${supabaseUrl}/rest/v1/newsletter_subscribers`, {
          method: "POST",
          headers: { ...headers, Prefer: "return=minimal" },
          body: JSON.stringify({ email: email.toLowerCase().trim(), created_at: (/* @__PURE__ */ new Date()).toISOString() })
        });
        if (!res.ok) return fail("Failed to subscribe");
        return ok({ success: true });
      }
      // -------------------------------------------------------------
      default:
        return corsError(400, `Unknown action: ${action}`, requestOrigin);
    }
  } catch (error) {
    console.error("User ops error:", error);
    return corsError(500, "Internal Server Error", requestOrigin);
  }
};

// api/_lib/adapter.ts
async function runHandler(handler2, req, res) {
  const rawReq = req;
  const hasWebBodyReader = typeof rawReq?.text === "function";
  const method = hasWebBodyReader ? rawReq.method : rawReq?.method || "POST";
  let body = "";
  const headers = {};
  try {
    if (hasWebBodyReader) {
      body = await rawReq.text();
      if (rawReq.headers && typeof rawReq.headers.forEach === "function") {
        rawReq.headers.forEach((value, key) => {
          headers[key] = value;
        });
      }
    } else {
      const rawBody = rawReq?.body;
      if (typeof rawBody === "string") body = rawBody;
      else if (rawBody && typeof rawBody === "object") body = JSON.stringify(rawBody);
      const httpHeaders = rawReq?.headers || {};
      for (const key of Object.keys(httpHeaders)) {
        const value = httpHeaders[key];
        headers[key] = Array.isArray(value) ? value.join(", ") : String(value ?? "");
      }
    }
  } catch (error) {
    console.error("[api] Failed to read request:", error);
    return respondWith({ statusCode: 400, headers: {}, body: JSON.stringify({ error: `Invalid request: ${error?.message || error}` }) }, res);
  }
  const event = {
    httpMethod: String(method || "POST").toUpperCase(),
    headers,
    body,
    queryStringParameters: rawReq?.query || {}
  };
  let result;
  try {
    result = await handler2(event, {});
  } catch (error) {
    console.error("[api] Handler threw:", error);
    return respondWith(
      {
        statusCode: 500,
        headers: {},
        body: JSON.stringify({ error: `Handler error: ${error?.message || error}` })
      },
      res
    );
  }
  const statusCode = result?.statusCode || 200;
  const responseBody = result?.body || "";
  const applyHeaders = (target) => {
    const resultHeaders = { ...result?.headers || {} };
    if (!("Content-Type" in resultHeaders) && responseBody) {
      resultHeaders["Content-Type"] = "application/json";
    }
    for (const [key, value] of Object.entries(resultHeaders)) {
      target[key] = value;
    }
  };
  if (res && typeof res.end === "function") {
    const nodeRes = res;
    if (typeof nodeRes.status === "function") nodeRes.status(statusCode);
    else nodeRes.statusCode = statusCode;
    applyHeaders(nodeRes);
    nodeRes.end(responseBody);
    return;
  }
  const responseHeaders = new Headers();
  applyHeaders(responseHeaders);
  return new Response(responseBody, { status: statusCode, headers: responseHeaders });
}
function respondWith(result, res) {
  const statusCode = result.statusCode || 500;
  const responseBody = result.body || "";
  const applyHeaders = (target) => {
    const resultHeaders = { ...result.headers || {} };
    if (!("Content-Type" in resultHeaders) && responseBody) {
      resultHeaders["Content-Type"] = "application/json";
    }
    for (const [key, value] of Object.entries(resultHeaders)) {
      target[key] = value;
    }
  };
  if (res && typeof res.end === "function") {
    if (typeof res.status === "function") res.status(statusCode);
    else res.statusCode = statusCode;
    applyHeaders(res);
    res.end(responseBody);
    return;
  }
  const responseHeaders = new Headers();
  applyHeaders(responseHeaders);
  return new Response(responseBody, { status: statusCode, headers: responseHeaders });
}

// scripts/.entries/user-ops.ts
async function user_ops_default(req, res) {
  return runHandler(handler, req, res);
}
export {
  user_ops_default as default
};
